GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2FsZXVsIiwiaWF0IjoxNzA2MTAzMjk4fQ.jfvF4Cl1y53KIaedJOGuVYY7Re-RByxDYMuOIRKlD7s

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Caleul"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2FsZXVsIiwiaWF0IjoxNzA2MTAzNDUxfQ.ipXEeZuB19lHMvQgOrGGOu_GM5m_KaFNvAjOBmpmPzc"
}